Models/Gift.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LG_10_Exercise_01.Models
{
    public class Gift
    {
        public long ID { get; set; }
        public string Gift_Name { get; set; }

        public string Details { get; set; }
        public int Price { get; set; }

        public virtual GiftCategory giftcategory { get; set; }

        public int GiftCategoryID { get; set; }
    }
}

Controllers/GiftsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using LG_10_Exercise_01.Models;

namespace LG_10_Exercise_01.Controllers
{
    public class GiftsController : Controller
    {
        private GiftDbContext db = new GiftDbContext();

        public ActionResult ImportGiftItems()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ImportGiftItems(string tbFilePath)
        {
            string strResponse;
            if (!string.IsNullOrEmpty(tbFilePath))
            {
                try
                {
                    System.Xml.Linq.XDocument xmlDoc = System.Xml.Linq.XDocument.Load(tbFilePath);

                    var gifts = from g in xmlDoc.Descendants("Gift")
                                select g;

                    foreach (var gift in gifts)
                    {
                        Gift newGift = new Gift();
                        newGift.Details = gift.Element("Details").Value;
                        newGift.Gift_Name = gift.Element("Name").Value;
                        newGift.GiftCategoryID = Convert.ToInt32(gift.Element("Category").Value);
                        newGift.Price = Convert.ToInt32(gift.Element("Price").Value);
                        db.Gifts.Add(newGift);
                        db.SaveChanges();
                    }
                    strResponse = "<font style='font-size:18pt;'><b>Gift items added successfully in the database.</b><br><br><br></font>";
                }
                catch (System.Exception ex)
                {
                    strResponse = "<font style='font-size:18pt;color:red;'><b>Invalid file path.</b><br><br><br></font>";
                }
                
            }
            else
                strResponse = "<font style='font-size:18pt;color:red;'><b>Please specify a valid file path.</b><br><br><br></font>";
            ViewBag.response = strResponse;
            return View();
        }

        [HttpPost]
        public ActionResult Index(int? GiftList, int? priceRange)
        {
            IEnumerable<Gift> dtGifts = (IEnumerable<Gift>)System.Runtime.Caching.MemoryCache.Default.Get("GiftList", null);

            if (dtGifts == null)
            {
                System.Runtime.Caching.MemoryCache.Default.Add("GiftList", getGifts(), System.DateTime.Now.AddMinutes(5), null);
                dtGifts = (IEnumerable<Gift>)System.Runtime.Caching.MemoryCache.Default.Get("GiftList", null);
            }

            var gifts = dtGifts;
            
            
         
            ViewBag.GiftList = new SelectList(db.GiftCategories, "GiftCategoryID", "strCategory");
            if (GiftList != null)
            {
                gifts = gifts.Where(g => g.GiftCategoryID == GiftList);
            }
            if (priceRange != null)
            {
                switch (priceRange)
                {
                    case 1:
                        gifts = gifts.Where(g => g.Price < 50);
                        break;
                    case 2:
                        gifts = gifts.Where(g => g.Price >= 50 && g.Price <= 100);
                        break;
                    case 3:
                        gifts = gifts.Where(g => g.Price > 100);
                        break;
                }
            }
            return PartialView("_FilteredGifts", gifts);
        }

        //
        // GET: /Gifts/
        public IEnumerable<Gift> getGifts()
        {
            var gifts = db.Gifts.Include(g=> g.giftcategory).ToList();
            return (gifts);
        }

        public ActionResult Index()
        {
            IEnumerable<Gift> dtGifts = (IEnumerable<Gift>)System.Runtime.Caching.MemoryCache.Default.Get("GiftList", null);
            ViewBag.method = "get";
                

            if (dtGifts == null)
            {
                System.Runtime.Caching.MemoryCache.Default.Add("GiftList", getGifts(), System.DateTime.Now.AddMinutes(2), null);
                dtGifts = (IEnumerable<Gift>)System.Runtime.Caching.MemoryCache.Default.Get("GiftList", null);

                var gifts = dtGifts;
                ViewBag.GiftList = new SelectList(db.GiftCategories, "GiftCategoryID", "strCategory");
                return View(gifts);
            }


            else
            {

                var gifts = dtGifts;
                ViewBag.GiftList = new SelectList(db.GiftCategories, "GiftCategoryID", "strCategory");
                return View(gifts);

            }
                    
        }

        //
        // GET: /Gifts/Details/5

        public ActionResult Details(long id = 0)
        {
            Gift gift = db.Gifts.Find(id);
            if (gift == null)
            {
                return HttpNotFound();
            }
            return View(gift);
        }

        //
        // GET: /Gifts/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.GiftCategoryID = new SelectList(db.GiftCategories, "GiftCategoryID", "strCategory");
            return View();
        }

        //
        // POST: /Gifts/Create

        [HttpPost]
        [Authorize]
        public ActionResult Create(Gift gift)
        {
            if (ModelState.IsValid)
            {
                db.Gifts.Add(gift);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GiftCategoryID = new SelectList(db.GiftCategories, "GiftCategoryID", "strCategory", gift.GiftCategoryID);
            return View(gift);
        }

        //
        // GET: /Gifts/Edit/5
        [Authorize]
        public ActionResult Edit(long id = 0)
        {
            Gift gift = db.Gifts.Find(id);
            if (gift == null)
            {
                return HttpNotFound();
            }
            ViewBag.GiftCategoryID = new SelectList(db.GiftCategories, "GiftCategoryID", "strCategory", gift.GiftCategoryID);
            return View(gift);
        }

        //
        // POST: /Gifts/Edit/5

        [HttpPost]
        [Authorize]
        public ActionResult Edit(Gift gift)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gift).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GiftCategoryID = new SelectList(db.GiftCategories, "GiftCategoryID", "strCategory", gift.GiftCategoryID);
            return View(gift);
        }

        //
        // GET: /Gifts/Delete/5
        [Authorize]
        public ActionResult Delete(long id = 0)
        {
            Gift gift = db.Gifts.Find(id);
            if (gift == null)
            {
                return HttpNotFound();
            }
            return View(gift);
        }

        //
        // POST: /Gifts/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(long id)
        {
            Gift gift = db.Gifts.Find(id);
            db.Gifts.Remove(gift);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }

        
        public ActionResult ShoppingCart(int id=0)
        {
            Gift gift;
            if (id != 0)
            {
                gift = db.Gifts.Find(id);
            }
            else
            {
                return View();
            }

            var gifts="";


            if (Session["items"] != null)
                gifts = Session["Items"].ToString() + gift.Gift_Name + "<br/>";
            else
            {
                gifts = gift.Gift_Name +  "<br/>";
            }

                      
            Session["Items"] =gifts;
            
            return View();
        }

    }
}

Views/Gifts/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

     <table style="width:98%;padding:0; border-collapse:collapse; margin-left:auto;margin-right:auto" border="0">
        <tr>
          <td>&nbsp;</td>
        </tr>

    
        <tr>
          <td style="font-size:12px; ">
@model LG_10_Exercise_01.Models.Gift

@{
    ViewBag.Title = "Create";
}



@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Gift</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Gift_Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Gift_Name)
            @Html.ValidationMessageFor(model => model.Gift_Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Details)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Details)
            @Html.ValidationMessageFor(model => model.Details)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.GiftCategoryID, "giftcategory")
        </div>
        <div class="editor-field">
            @Html.DropDownList("GiftCategoryID", String.Empty)
            @Html.ValidationMessageFor(model => model.GiftCategoryID)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
              </td>
        </tr>
        
      </table>

Views/Gifts/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table style="width:98%;padding:0; border-collapse:collapse; margin-left:auto;margin-right:auto" border="0">
        <tr>
          <td>&nbsp;</td>
        </tr>

    
        <tr>
          <td style="font-size:12px; ">
@model LG_10_Exercise_01.Models.Gift

@{
    ViewBag.Title = "Delete";
}


<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Gift</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Gift_Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Gift_Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Details)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Details)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Price)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.giftcategory.strCategory)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.giftcategory.strCategory)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}
              </td>
        </tr>
        
      </table>

Views/Gifts/Details.cshtml
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

     <table style="width:98%;padding:0; border-collapse:collapse; margin-left:auto;margin-right:auto" border="0">
        <tr>
          <td>&nbsp;</td>
        </tr>

    
        <tr>
          <td style="font-size:12px; ">
              @model LG_10_Exercise_01.Models.Gift

@{
    ViewBag.Title = "Details";
}



<fieldset>
    <legend>Gift</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Gift_Name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Gift_Name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Details)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Details)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Price)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Price)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.giftcategory.strCategory)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.giftcategory.strCategory)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")|
       @Html.ActionLink("Add to Shopping Cart", "ShoppingCart", new { id = Model.ID })   
</p>
              </td>
        </tr>
        
      </table>

Views/Gifts/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

  <table style="width:98%;padding:0; border-collapse:collapse; margin-left:auto;margin-right:auto" border="0">
        <tr>
          <td>&nbsp;</td>
        </tr>

    
        <tr>
          <td style="font-size:12px; ">
              @model LG_10_Exercise_01.Models.Gift

@{
    ViewBag.Title = "Edit";
}



@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Gift</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Gift_Name)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Gift_Name)
            @Html.ValidationMessageFor(model => model.Gift_Name)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Details)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Details)
            @Html.ValidationMessageFor(model => model.Details)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Price)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Price)
            @Html.ValidationMessageFor(model => model.Price)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.GiftCategoryID, "giftcategory")
        </div>
        <div class="editor-field">
            @Html.DropDownList("GiftCategoryID", String.Empty)
            @Html.ValidationMessageFor(model => model.GiftCategoryID)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
              </td>
        </tr>
        
      </table>

Views/Gifts/ImportGiftItems.cshtml
@{
    ViewBag.Title = "ImportGiftItems";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<table style="width:98%;padding:0; border-collapse:collapse; margin-left:auto;margin-right:auto" border="0">
        <tr>
          <td>&nbsp;</td>
        </tr>

    
        <tr>
          <td style="font-size:12px; ">
@{
    ViewBag.Title = "ImportGiftItems";
}
@using (Html.BeginForm())
{
    if (string.IsNullOrEmpty(ViewBag.response))
    { 
<font style="font-size: 18pt;">
Path of XML file: <br />
    <input type="text" id="tbFilePath" name="tbFilePath"/>
    <br />
    <input type="submit" value="Add"/>
    </font>
    }
    else
    {
        @Html.Raw(ViewBag.response);

    }
}
                </td>
        </tr>
        
      </table>

Views/Gifts/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<table style="width: 98%; padding: 0; border-collapse: collapse; margin-left: auto; margin-right: auto" border="0">
    <tr>
        <td>&nbsp;</td>
    </tr>


    <tr>
        <td style="font-size: 12px;">
            @model IEnumerable<LG_10_Exercise_01.Models.Gift>

            @{
                ViewBag.Title = "Index";
            }

            @section scripts{
                <script src="~/Scripts/jquery-ui-1.8.20.js"></script>
                <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.js")"></script>
            }

            <p style="color: #f5eb8e; font-size: medium;">
                @Html.ActionLink("Create New", "Create")
                @Html.ActionLink("Import Gift Items", "ImportGiftItems")
            </p>
            <p>

                

                @using (Ajax.BeginForm("Index", "Gifts",
new AjaxOptions
{
    InsertionMode = InsertionMode.Replace,
    HttpMethod = "POST",
    LoadingElementId = "ajax-loader",
    UpdateTargetId = "filterResultDiv",
}))
                {
                    <div style="float: left; padding: 5px; margin: 10px; font-weight: bold;">
                        Filter by Category
                    </div>
                    <div style="float: left; padding: 5px; margin: 10px; font-weight: bold;">
                        @Html.DropDownList("GiftList", "All")
                    </div>
                    <div style="float: left; padding: 5px; margin: 10px; font-weight: bold;">
                        Price Range
                    </div>
                    <div style="float: left; padding: 5px; margin: 10px; font-weight: bold;">
                        <select id="priceRange" name="priceRange">
                            <option value="null" selected="selected">All</option>
                            <option value="1">Less than $50</option>
                            <option value="2">Between $50 and $100</option>
                            <option value="3">More than $100</option>
                        </select>
                    </div>
                    <div style="float: left; padding: 5px; margin: 10px; font-weight: bold;">
                        <input type="submit" value="Filter Gifts" />
                    </div>
                    <br />

                    <span id="ajax-loader" style="display:none;">Filtering gifts. Please wait...</span> 
                }
                
            </p>
            <br />

            <p>
                <div id="filterResultDiv" style="padding: 5px; margin: 10px;">

                  @if (ViewBag.method == "get") {
                      Html.RenderPartial("_FilteredGifts", Model);
                  }

                </div>
            </p>
        </td>
    </tr>


</table>


Views/Gifts/ShoppingCart.cshtml
@{
    ViewBag.Title = "ShoppingCart";
}


<h2>Shopping Cart</h2>
@{
    if (Session["Items"] != null)
    {
        var gifts = Session["Items"].ToString();
        @Html.Raw(gifts);
    
    }
    else
    {
        <h4>No items found.</h4>
    }
        
}


Views/Gifts/_FilteredGifts.cshtml
  @model IEnumerable<LG_10_Exercise_01.Models.Gift>
@section scripts{
    <script src="~/Scripts/Highlight.js"></script>
}
<link href="~/Content/Custom.css" rel="stylesheet" />
<table border="1" style="width: 100%; border-collapse: separate; border-color: black; border-style: solid; border-width: 1px;">

                        @{
                            if (Model.Count<LG_10_Exercise_01.Models.Gift>() > 0)
                            {
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Gift_Name)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Details)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Price)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.giftcategory.strCategory)
                                </th>
                                <th></th>
                            </tr >
    
                                foreach (var item in Model)
                                {
                            <tr class="row">
                                <td>
                                    @Html.DisplayFor(modelItem => item.Gift_Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Details)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Price)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.giftcategory.strCategory)
                                </td>
                                <td>
                                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
            @Html.ActionLink("Details", "Details", new { id = item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ID })
                                </td>
                            </tr>
                                }
                            }
                            else
                            {
                            <font style="color: red;"><h3>No gifts exists.</h3></font>
                            }
        
                        }



                    </table>